Q1 — What is the total revenue generated by male vs female customers?

SELECT 
    gender,
    SUM(purchase_amount) AS total_revenue
FROM customer_shopping_data
GROUP BY gender;

Q2 — Which customers used a discount but still spent more than the average purchase amount?

SELECT 
    customer_id,
    purchase_amount
FROM customer_shopping_data
WHERE discount_applied = 'Yes'
AND purchase_amount >= (
    SELECT AVG(purchase_amount)
    FROM customer_shopping_data
);

Q3 — Which are the top 5 products with the highest average review rating?

SELECT 
    item_purchased,
    ROUND(AVG(review_rating),2) AS avg_product_rating
FROM customer_shopping_data
GROUP BY item_purchased
ORDER BY avg_product_rating DESC
LIMIT 5;

Q4 — Compare the average purchase amount between Standard and Express shipping.

SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount),2) AS avg_purchase_amount
FROM customer_shopping_data
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

Q5 — Do subscribed customers spend more than non-subscribed customers?

SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount),2) AS avg_spend,
    ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_shopping_data
GROUP BY subscription_status
ORDER BY total_revenue DESC;

Q6 — Which 5 products have the highest percentage of purchases with discounts?

SELECT 
    item_purchased,
    ROUND(
        100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS discount_rate
FROM customer_shopping_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

Q7 — Segment customers into New, Returning, and Loyal customers.

WITH customer_segments AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_shopping_data
)

SELECT 
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_segments
GROUP BY customer_segment;

Q8 — What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer_shopping_data
    GROUP BY category, item_purchased
)

SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

Q9 — Are repeat buyers more likely to subscribe?

SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer_shopping_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

Q10 — What is the revenue contribution of each age group?

SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_shopping_data
GROUP BY age_group
ORDER BY total_revenue DESC;

Q11 — Which locations generate the highest revenue?

SELECT 
    location,
    SUM(purchase_amount) AS total_revenue
FROM customer_shopping_data
GROUP BY location
ORDER BY total_revenue DESC
LIMIT 10;

Q12 — Which product category generates the most revenue?

SELECT 
    category,
    SUM(purchase_amount) AS total_revenue,
    COUNT(*) AS total_orders
FROM customer_shopping_data
GROUP BY category
ORDER BY total_revenue DESC;